# =====================================================================
# run_vip_check.ps1 — S2 PS/PL 协同仿真环境 · 一键生成 + 编译 + 运行 + 判据
#
# 步骤：
#   1) vivado -mode batch 生成 AXI VIP（首次或 -Rebuild；生成物不入版本控制）
#   2) xvlog 编译 VIP 包/wrapper + 示例从端 + PS 序列 TB
#   3) xelab 用预编译库 -L axi_vip_v1_1_11 -L xilinx_vip 详细化
#   4) xsim 运行，判据取日志里的 [VIP-RESULT] ... status=PASS
#
# 用法：.\run_vip_check.ps1 [-Rebuild]
# 前置：vivado/xvlog/xelab/xsim 在 PATH。
# =====================================================================
param([switch]$Rebuild)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot

foreach ($tool in 'vivado', 'xvlog', 'xelab', 'xsim') {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        throw "$tool not found in PATH. Run: call D:\software\vivado2021\Vivado\2021.2\settings64.bat"
    }
}

$LogDir = Join-Path $PSScriptRoot 'logs'
$GenDir = Join-Path $PSScriptRoot 'gen'
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

$IpPkg = $null
$IpWrap = $null
if (Test-Path $GenDir) {
    $found = Get-ChildItem -LiteralPath $GenDir -Recurse -Filter 'axi_vip_mst_pkg.sv' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($found) { $IpPkg = $found.FullName }
    $found = Get-ChildItem -LiteralPath $GenDir -Recurse -Filter 'axi_vip_mst.sv' -ErrorAction SilentlyContinue |
             Where-Object { $_.DirectoryName -notmatch '\\hdl$' } | Select-Object -First 1
    if ($found) { $IpWrap = $found.FullName }
}

if ($Rebuild -or -not $IpPkg -or -not $IpWrap) {
    Write-Host '[1/4] 生成 AXI VIP（vivado -mode batch，首次约 1 分钟）'
    if (Test-Path $GenDir) { Remove-Item -LiteralPath $GenDir -Recurse -Force }
    & vivado -mode batch -nojournal -nolog -notrace -source build_axi_vip.tcl *> (Join-Path $LogDir 'vip.build.log')
    $found = Get-ChildItem -LiteralPath $GenDir -Recurse -Filter 'axi_vip_mst_pkg.sv' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($found) { $IpPkg = $found.FullName }
    $found = Get-ChildItem -LiteralPath $GenDir -Recurse -Filter 'axi_vip_mst.sv' -ErrorAction SilentlyContinue |
             Where-Object { $_.DirectoryName -notmatch '\\hdl$' } | Select-Object -First 1
    if ($found) { $IpWrap = $found.FullName }
    if (-not $IpPkg -or -not $IpWrap) { throw "VIP 生成失败，见 logs\vip.build.log" }
} else {
    Write-Host '[1/4] 复用已有 VIP 生成产物（要重建加 -Rebuild）'
}

# gen/ 是重建产物：确保目录内有局部忽略规则（-Rebuild 会清空 gen/，此处自动补回）
$GenIgnore = Join-Path $GenDir '.gitignore'
if (-not (Test-Path -LiteralPath $GenIgnore)) {
    $ignoreText = "# AXI VIP generation outputs: regenerated by build_axi_vip.tcl, not versioned.`n" +
                  "# Directory-scoped ignore (affects only gen/), does not touch the repo root .gitignore.`n*`n!.gitignore`n"
    [IO.File]::WriteAllText($GenIgnore, $ignoreText, [Text.ASCIIEncoding]::new())
}
Write-Host ("      pkg : {0}" -f $IpPkg.Replace("$PSScriptRoot\", ''))
Write-Host ("      wrap: {0}" -f $IpWrap.Replace("$PSScriptRoot\", ''))

foreach ($dir in 'work', 'xsim.dir') {
    $path = Join-Path $PSScriptRoot $dir
    if (Test-Path -LiteralPath $path) { Remove-Item -LiteralPath $path -Recurse -Force }
}

Write-Host '[2/4] xvlog（带 -L 以便编译期解析 xilinx_vip 预编译包）'
$srcs = @($IpPkg, $IpWrap, 'axi_regs_demo.sv', 'tb_axi_ps_seq.sv')
& xvlog -sv -L xilinx_vip -L axi_vip_v1_1_11 -work work @srcs *> (Join-Path $LogDir 'vip.xvlog.log')
if ($LASTEXITCODE -ne 0) { throw "xvlog 失败，见 logs\vip.xvlog.log" }

Write-Host '[3/4] xelab（用预编译 VIP 库）'
& xelab -relax -timescale 1ns/1ps -snapshot sn_vip -debug typical `
    -L axi_vip_v1_1_11 -L xilinx_vip work.tb_axi_ps_seq *> (Join-Path $LogDir 'vip.xelab.log')
if ($LASTEXITCODE -ne 0) { throw "xelab 失败，见 logs\vip.xelab.log" }

Write-Host '[4/4] xsim（执行 PS 侧读写序列）'
$simLog = Join-Path $LogDir 'vip.xsim.log'
& xsim sn_vip -runall *> $simLog
$simText = Get-Content -LiteralPath $simLog -Raw

$summary = [regex]::Matches($simText, '\[VIP-RESULT\][^\r\n]*') | ForEach-Object { $_.Value }
foreach ($line in $summary) { Write-Host "  $line" }

$failed = [regex]::Matches($simText, '\[VIP-CHK\] FAIL[^\r\n]*') | ForEach-Object { $_.Value }
foreach ($line in $failed) { Write-Host "  $line" }

if ($simText -match '\[VIP-RESULT\].*status=PASS') {
    Write-Host ''
    Write-Host '  [VIP CHECK] PASS'
    exit 0
}
Write-Host ''
Write-Host ("  [VIP CHECK] FAIL（日志：{0}）" -f $simLog)
exit 1
